from typing import Any, Dict, Generic, List, Optional, TypeVar

T = TypeVar("T")

class IRepository(Generic[T]):
    def get_by_id(self, id: Any, load_relationships: bool = True) -> Optional[T]: ...
    def get_all(self, skip: int = 0, limit: int = 100) -> List[T]: ...
    def create(self, **kwargs: Any) -> T: ...
    def update(self, id: Any, **kwargs: Any) -> Optional[T]: ...
    def delete(self, id: Any) -> bool: ...
    def exists(self, **kwargs: Any) -> bool: ...
    def count(self, **kwargs: Any) -> int: ...

class BaseRepository(IRepository[T], Generic[T]):
    db: Any
    model: Any
    logger: Any
    def __init__(self, db: Any, model: Any) -> None: ...
    @property
    def dialect_name(self) -> str: ...
    def get_by_id(self, id: Any, load_relationships: bool = True) -> Optional[T]: ...
    def get_all(self, skip: int = 0, limit: int = 100) -> List[T]: ...
    def create(self, **kwargs: Any) -> T: ...
    def update(self, id: Any, **kwargs: Any) -> Optional[T]: ...
    def delete(self, id: Any) -> bool: ...
    def exists(self, **kwargs: Any) -> bool: ...
    def count(self, **kwargs: Any) -> int: ...
    def find_by(self, **kwargs: Any) -> List[T]: ...
    def find_one_by(self, **kwargs: Any) -> Optional[T]: ...
    def bulk_create(self, entities: List[Dict[str, Any]]) -> List[T]: ...
    def bulk_update(self, updates: List[Dict[str, Any]]) -> int: ...
    def _apply_eager_loading(self, query: Any) -> Any: ...
    def _build_query(self) -> Any: ...
    def _execute_query(self, query: Any) -> List[T]: ...
    def _execute_scalar(self, query: Any) -> Any: ...
