from typing import Any, Callable, Optional, ParamSpec, TypeVar, Union

P = ParamSpec("P")
R = TypeVar("R")

class CachedRepositoryMixin:
    _cache_service: Any
    _cache_prefix: str
    _cache_enabled: bool
    def init_cache(self, cache_service: Optional[Any] = ...) -> None: ...
    @property
    def cache_service(self) -> Optional[Any]: ...
    def _generate_cache_key(self, method_name: str, *args: Any, **kwargs: Any) -> str: ...
    def invalidate_entity_cache(self, entity_id: Union[int, str]) -> None: ...
    def invalidate_all_cache(self) -> None: ...

def cached_method(ttl: Optional[int] = ..., tier: str = ...) -> Callable[[Callable[P, R]], Callable[P, R]]: ...
