import logging
from typing import Any, Callable, ContextManager, Dict, Optional, ParamSpec, TypeVar

from sqlalchemy.orm import Session

P = ParamSpec("P")
R = TypeVar("R")

class BaseService:
    db: Session
    cache: Optional[Any]
    logger: logging.Logger
    def __init__(self, db: Session, cache: Optional[Any] = ...) -> None: ...
    def transaction(self) -> ContextManager[Session]: ...
    @staticmethod
    def measure_operation(operation_name: str) -> Callable[[Callable[P, R]], Callable[P, R]]: ...
    def get_metrics(self) -> Dict[str, Any]: ...
    def reset_metrics(self) -> None: ...
    def invalidate_cache(self, *keys: str) -> None: ...
    def invalidate_pattern(self, pattern: str) -> None: ...
    def log_operation(self, operation: str, **context: Any) -> None: ...
