name: Use Node for frontend
description: Setup Node and npm cache for frontend
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version-file: frontend/.nvmrc
        cache: npm
        cache-dependency-path: frontend/package-lock.json

    - name: Show versions and enforce >=22
      shell: bash
      run: |
        node -v
        npm -v
        major=$(node -p "process.versions.node.split('.')[0]")
        if [ "$major" -lt 22 ]; then
          echo "Expected Node >=22, got $(node -v)"
          exit 1
        fi
