name: Use Node for frontend
description: Setup Node and npm cache for frontend
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: npm
        cache-dependency-path: frontend/package-lock.json
    - name: Print Node versions (sanity)
      shell: bash
      run: |
        echo "Node version: $(node -v)"
        echo "npm version: $(npm -v)"
        # Fail fast if Node is less than 22
        NODE_VERSION=$(node -v | sed 's/v//')
        NODE_MAJOR=$(echo $NODE_VERSION | cut -d. -f1)
        if [ "$NODE_MAJOR" -lt 22 ]; then
          echo "::error::Node version must be >= 22, got v$NODE_VERSION"
          exit 1
        fi
