name: Use Node for frontend
description: Setup Node (default 22.x) with npm cache for frontend
inputs:
  node-version:
    required: false
    default: '22.x'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm
        cache-dependency-path: frontend/package-lock.json
    - shell: bash
      run: |
        echo "Node: $(node -v)"
        echo "npm:  $(npm -v)"
