name: Use Node for frontend
description: Set Node and npm cache for the frontend workspace
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: npm
        cache-dependency-path: frontend/package-lock.json

    - name: Show Node/NPM versions
      shell: bash
      run: |
        node -v
        npm -v

    - name: Enforce Node >= 22
      shell: bash
      run: |
        MAJOR=$(node -p "process.versions.node.split('.')[0]")
        if [ "$MAJOR" -lt 22 ]; then
          echo "Expected Node >= 22, got $(node -v)"
          exit 1
        fi
