"""Add booking enhancements

Revision ID: 435556c30c6b
Revises: 
Create Date: 2025-06-08 14:26:53.350230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '435556c30c6b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip the areas_of_service change - it's working fine as is
    
    # Add new columns to bookings table for enhanced booking features
    op.add_column('bookings', sa.Column('service_id', sa.Integer(), nullable=True))
    op.add_column('bookings', sa.Column('cancellation_deadline', sa.DateTime(), nullable=True))
    op.add_column('bookings', sa.Column('cancelled_at', sa.DateTime(), nullable=True))
    op.add_column('bookings', sa.Column('cancellation_reason', sa.String(), nullable=True))
    
    # Add foreign key constraint for service_id
    op.create_foreign_key(
        'fk_bookings_service_id', 
        'bookings', 
        'services', 
        ['service_id'], 
        ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove foreign key constraint
    op.drop_constraint('fk_bookings_service_id', 'bookings', type_='foreignkey')
    
    # Remove columns
    op.drop_column('bookings', 'cancellation_reason')
    op.drop_column('bookings', 'cancelled_at')
    op.drop_column('bookings', 'cancellation_deadline')
    op.drop_column('bookings', 'service_id')
    # ### end Alembic commands ###