"""Neighborhood display-layer configuration for NYC NTA polygons."""

from __future__ import annotations

import re

NEIGHBORHOOD_MAPPING: dict[tuple[str, str], str | None] = {
    # Manhattan
    ("Manhattan", "Central Park"): None,
    ("Manhattan", "Highbridge Park"): None,
    ("Manhattan", "Inwood Hill Park"): None,
    ("Manhattan", "Randall's Island"): None,
    ("Manhattan", "The Battery-Governors Island-Ellis Island-Liberty Island"): None,
    ("Manhattan", "United Nations"): None,
    ("Manhattan", "East Harlem (North)"): "East Harlem",
    ("Manhattan", "East Harlem (South)"): "East Harlem",
    ("Manhattan", "Harlem (North)"): "Harlem",
    ("Manhattan", "Harlem (South)"): "Harlem",
    ("Manhattan", "Upper East Side-Carnegie Hill"): "Upper East Side",
    ("Manhattan", "Upper East Side-Yorkville"): "Upper East Side",
    ("Manhattan", "Upper West Side (Central)"): "Upper West Side",
    ("Manhattan", "Upper West Side-Lincoln Square"): "Upper West Side",
    ("Manhattan", "Upper West Side-Manhattan Valley"): "Upper West Side",
    ("Manhattan", "Washington Heights (North)"): "Washington Heights",
    ("Manhattan", "Washington Heights (South)"): "Washington Heights",
    ("Manhattan", "Chelsea-Hudson Yards"): "Chelsea / Hudson Yards",
    ("Manhattan", "Chinatown-Two Bridges"): "Chinatown / Two Bridges",
    ("Manhattan", "East Midtown-Turtle Bay"): "Midtown East / Turtle Bay",
    ("Manhattan", "Financial District-Battery Park City"): "Financial District / Battery Park City",
    ("Manhattan", "Gramercy"): "Gramercy Park",
    ("Manhattan", "Hamilton Heights-Sugar Hill"): "Hamilton Heights",
    ("Manhattan", "Manhattanville-West Harlem"): "West Harlem / Manhattanville",
    ("Manhattan", "Midtown South-Flatiron-Union Square"): "Flatiron / NoMad / Union Square",
    ("Manhattan", "Midtown-Times Square"): "Midtown",
    ("Manhattan", "Murray Hill-Kips Bay"): "Murray Hill / Kips Bay",
    ("Manhattan", "SoHo-Little Italy-Hudson Square"): "SoHo / Hudson Square / Little Italy",
    ("Manhattan", "Stuyvesant Town-Peter Cooper Village"): "Stuyvesant Town / Peter Cooper Village",
    ("Manhattan", "Tribeca-Civic Center"): "Tribeca / Civic Center",
    (
        "Manhattan",
        "Upper East Side-Lenox Hill-Roosevelt Island",
    ): "Upper East Side / Roosevelt Island",
    ("Manhattan", "East Village"): "East Village",
    ("Manhattan", "Greenwich Village"): "Greenwich Village",
    ("Manhattan", "Hell's Kitchen"): "Hell's Kitchen",
    ("Manhattan", "Inwood"): "Inwood",
    ("Manhattan", "Lower East Side"): "Lower East Side",
    ("Manhattan", "Morningside Heights"): "Morningside Heights",
    ("Manhattan", "West Village"): "West Village",
    # Brooklyn
    ("Brooklyn", "Barren Island-Floyd Bennett Field"): None,
    ("Brooklyn", "Brooklyn Navy Yard"): None,
    ("Brooklyn", "Calvert Vaux Park"): None,
    ("Brooklyn", "Canarsie Park & Pier"): None,
    ("Brooklyn", "Dyker Beach Park"): None,
    ("Brooklyn", "Green-Wood Cemetery"): None,
    ("Brooklyn", "Highland Park-Cypress Hills Cemeteries (South)"): None,
    ("Brooklyn", "Holy Cross Cemetery"): None,
    ("Brooklyn", "Jamaica Bay (West)"): None,
    ("Brooklyn", "Lincoln Terrace Park"): None,
    ("Brooklyn", "Marine Park-Plumb Island"): None,
    ("Brooklyn", "McGuire Fields"): None,
    ("Brooklyn", "Prospect Park"): None,
    ("Brooklyn", "Shirley Chisholm State Park"): None,
    ("Brooklyn", "The Evergreens Cemetery"): None,
    ("Brooklyn", "Bay Ridge"): "Bay Ridge",
    ("Brooklyn", "Fort Hamilton"): "Bay Ridge",
    ("Brooklyn", "Bedford-Stuyvesant (East)"): "Bedford-Stuyvesant",
    ("Brooklyn", "Bedford-Stuyvesant (West)"): "Bedford-Stuyvesant",
    ("Brooklyn", "Bushwick (East)"): "Bushwick",
    ("Brooklyn", "Bushwick (West)"): "Bushwick",
    ("Brooklyn", "Crown Heights (North)"): "Crown Heights",
    ("Brooklyn", "Crown Heights (South)"): "Crown Heights",
    ("Brooklyn", "East Flatbush-Erasmus"): "East Flatbush",
    ("Brooklyn", "East Flatbush-Farragut"): "East Flatbush",
    ("Brooklyn", "East Flatbush-Remsen Village"): "East Flatbush",
    ("Brooklyn", "East Flatbush-Rugby"): "East Flatbush",
    ("Brooklyn", "East New York (North)"): "East New York",
    ("Brooklyn", "East New York-City Line"): "East New York",
    ("Brooklyn", "East New York-New Lots"): "East New York",
    ("Brooklyn", "Gravesend (South)"): "Gravesend",
    ("Brooklyn", "Gravesend (West)"): "Gravesend",
    ("Brooklyn", "Sunset Park (Central)"): "Sunset Park",
    ("Brooklyn", "Sunset Park (East)-Borough Park (West)"): "Sunset Park",
    ("Brooklyn", "Sunset Park (West)"): "Sunset Park",
    (
        "Brooklyn",
        "Carroll Gardens-Cobble Hill-Gowanus-Red Hook",
    ): "Carroll Gardens / Cobble Hill / Gowanus / Red Hook",
    ("Brooklyn", "Coney Island-Sea Gate"): "Coney Island / Seagate",
    ("Brooklyn", "Downtown Brooklyn-DUMBO-Boerum Hill"): "Downtown Brooklyn / DUMBO / Boerum Hill",
    ("Brooklyn", "Flatbush (West)-Ditmas Park-Parkville"): "Ditmas Park",
    ("Brooklyn", "Gravesend (East)-Homecrest"): "Gravesend / Homecrest",
    ("Brooklyn", "Mapleton-Midwood (West)"): "Mapleton",
    ("Brooklyn", "Marine Park-Mill Basin-Bergen Beach"): "Marine Park / Mill Basin / Bergen Beach",
    ("Brooklyn", "Prospect Lefferts Gardens-Wingate"): "Prospect Lefferts Gardens",
    (
        "Brooklyn",
        "Sheepshead Bay-Manhattan Beach-Gerritsen Beach",
    ): "Sheepshead Bay / Manhattan Beach / Gerritsen Beach",
    ("Brooklyn", "Spring Creek-Starrett City"): "Spring Creek / Starrett City",
    ("Brooklyn", "Windsor Terrace-South Slope"): "Windsor Terrace",
    ("Brooklyn", "Bath Beach"): "Bath Beach",
    ("Brooklyn", "Bensonhurst"): "Bensonhurst",
    ("Brooklyn", "Borough Park"): "Borough Park",
    ("Brooklyn", "Brighton Beach"): "Brighton Beach",
    ("Brooklyn", "Brooklyn Heights"): "Brooklyn Heights",
    ("Brooklyn", "Brownsville"): "Brownsville",
    ("Brooklyn", "Canarsie"): "Canarsie",
    ("Brooklyn", "Clinton Hill"): "Clinton Hill",
    ("Brooklyn", "Cypress Hills"): "Cypress Hills",
    ("Brooklyn", "Dyker Heights"): "Dyker Heights",
    ("Brooklyn", "East Williamsburg"): "East Williamsburg",
    ("Brooklyn", "Flatbush"): "Flatbush",
    ("Brooklyn", "Flatlands"): "Flatlands",
    ("Brooklyn", "Fort Greene"): "Fort Greene",
    ("Brooklyn", "Greenpoint"): "Greenpoint",
    ("Brooklyn", "Kensington"): "Kensington",
    ("Brooklyn", "Madison"): "Madison",
    ("Brooklyn", "Midwood"): "Midwood",
    ("Brooklyn", "Ocean Hill"): "Ocean Hill",
    ("Brooklyn", "Park Slope"): "Park Slope",
    ("Brooklyn", "Prospect Heights"): "Prospect Heights",
    ("Brooklyn", "South Williamsburg"): "South Williamsburg",
    ("Brooklyn", "Williamsburg"): "Williamsburg",
    # Bronx
    ("Bronx", "Bronx Park"): None,
    ("Bronx", "Claremont Park"): None,
    ("Bronx", "Crotona Park"): None,
    ("Bronx", "Ferry Point Park-St. Raymond Cemetery"): None,
    ("Bronx", "Hart Island"): None,
    ("Bronx", "Hutchinson Metro Center"): None,
    ("Bronx", "North & South Brother Islands"): None,
    ("Bronx", "Pelham Bay Park"): None,
    ("Bronx", "Rikers Island"): None,
    ("Bronx", "Soundview Park"): None,
    ("Bronx", "Van Cortlandt Park"): None,
    ("Bronx", "Woodlawn Cemetery"): None,
    ("Bronx", "Yankee Stadium-Macombs Dam Park"): None,
    ("Bronx", "Kingsbridge Heights-Van Cortlandt Village"): "Kingsbridge / Marble Hill",
    ("Bronx", "Kingsbridge-Marble Hill"): "Kingsbridge / Marble Hill",
    ("Bronx", "Soundview-Bruckner-Bronx River"): "Soundview",
    ("Bronx", "Soundview-Clason Point"): "Soundview",
    ("Bronx", "Castle Hill-Unionport"): "Castle Hill",
    ("Bronx", "Claremont Village-Claremont (East)"): "Claremont Village",
    ("Bronx", "Concourse-Concourse Village"): "Concourse",
    ("Bronx", "Eastchester-Edenwald-Baychester"): "Eastchester / Edenwald / Baychester",
    ("Bronx", "Mott Haven-Port Morris"): "Mott Haven / Port Morris",
    ("Bronx", "Mount Eden-Claremont (West)"): "Mount Eden / Claremont",
    ("Bronx", "Pelham Bay-Country Club-City Island"): "Pelham Bay / Country Club / City Island",
    ("Bronx", "Pelham Parkway-Van Nest"): "Pelham Parkway / Van Nest",
    ("Bronx", "Riverdale-Spuyten Duyvil"): "Riverdale / Spuyten Duyvil",
    ("Bronx", "Throgs Neck-Schuylerville"): "Throgs Neck / Schuylerville",
    ("Bronx", "University Heights (North)-Fordham"): "University Heights / Fordham",
    ("Bronx", "University Heights (South)-Morris Heights"): "University Heights / Morris Heights",
    ("Bronx", "Wakefield-Woodlawn"): "Wakefield / Woodlawn",
    ("Bronx", "Williamsbridge-Olinville"): "Williamsbridge",
    ("Bronx", "Allerton"): "Allerton",
    ("Bronx", "Bedford Park"): "Bedford Park",
    ("Bronx", "Belmont"): "Belmont",
    ("Bronx", "Co-op City"): "Co-op City",
    ("Bronx", "Crotona Park East"): "Crotona Park East",
    ("Bronx", "Fordham Heights"): "Fordham Heights",
    ("Bronx", "Highbridge"): "Highbridge",
    ("Bronx", "Hunts Point"): "Hunts Point",
    ("Bronx", "Longwood"): "Longwood",
    ("Bronx", "Melrose"): "Melrose",
    ("Bronx", "Morris Park"): "Morris Park",
    ("Bronx", "Morrisania"): "Morrisania",
    ("Bronx", "Mount Hope"): "Mount Hope",
    ("Bronx", "Norwood"): "Norwood",
    ("Bronx", "Parkchester"): "Parkchester",
    ("Bronx", "Pelham Gardens"): "Pelham Gardens",
    ("Bronx", "Tremont"): "Tremont",
    ("Bronx", "West Farms"): "West Farms",
    ("Bronx", "Westchester Square"): "Westchester Square",
    # Queens
    ("Queens", "Alley Pond Park"): None,
    ("Queens", "Astoria Park"): None,
    ("Queens", "Calvary & Mount Zion Cemeteries"): None,
    ("Queens", "Cunningham Park"): None,
    ("Queens", "Flushing Meadows-Corona Park"): None,
    ("Queens", "Forest Park"): None,
    ("Queens", "Fort Totten"): None,
    ("Queens", "Highland Park-Cypress Hills Cemeteries (North)"): None,
    ("Queens", "Jacob Riis Park-Fort Tilden-Breezy Point Tip"): None,
    ("Queens", "Jamaica Bay (East)"): None,
    ("Queens", "John F. Kennedy International Airport"): None,
    ("Queens", "Kissena Park"): None,
    ("Queens", "LaGuardia Airport"): None,
    ("Queens", "Middle Village Cemetery"): None,
    ("Queens", "Montefiore Cemetery"): None,
    ("Queens", "Mount Hebron & Cedar Grove Cemeteries"): None,
    ("Queens", "Mount Olivet & All Faiths Cemeteries"): None,
    ("Queens", "Rockaway Community Park"): None,
    ("Queens", "Spring Creek Park"): None,
    ("Queens", "St. John Cemetery"): None,
    ("Queens", "St. Michael's Cemetery"): None,
    ("Queens", "Sunnyside Yards (North)"): None,
    ("Queens", "Sunnyside Yards (South)"): None,
    ("Queens", "Astoria (Central)"): "Astoria",
    ("Queens", "Astoria (East)-Woodside (North)"): "Astoria",
    ("Queens", "Astoria (North)-Ditmars-Steinway"): "Astoria",
    ("Queens", "Old Astoria-Hallets Point"): "Astoria",
    ("Queens", "Baisley Park"): "South Jamaica",
    ("Queens", "South Jamaica"): "South Jamaica",
    ("Queens", "Ozone Park"): "Ozone Park",
    ("Queens", "Ozone Park (North)"): "Ozone Park",
    ("Queens", "Springfield Gardens (North)-Rochdale Village"): "Springfield Gardens",
    ("Queens", "Springfield Gardens (South)-Brookville"): "Springfield Gardens",
    ("Queens", "Bay Terrace-Clearview"): "Clearview / Bay Terrace",
    (
        "Queens",
        "Breezy Point-Belle Harbor-Rockaway Park-Broad Channel",
    ): "Rockaway Park / Belle Harbor / Broad Channel / Breezy Point",
    ("Queens", "Douglaston-Little Neck"): "Douglaston / Little Neck",
    ("Queens", "Far Rockaway-Bayswater"): "Far Rockaway / Bayswater",
    ("Queens", "Flushing-Willets Point"): "Flushing",
    ("Queens", "Fresh Meadows-Utopia"): "Fresh Meadows / Utopia",
    ("Queens", "Glen Oaks-Floral Park-New Hyde Park"): "Glen Oaks / Floral Park / New Hyde Park",
    ("Queens", "Howard Beach-Lindenwood"): "Howard Beach",
    ("Queens", "Jamaica Estates-Holliswood"): "Jamaica Estates",
    ("Queens", "Jamaica Hills-Briarwood"): "Jamaica Hills / Briarwood",
    ("Queens", "Long Island City-Hunters Point"): "Long Island City / Hunters Point",
    ("Queens", "Murray Hill-Broadway Flushing"): "Murray Hill (Queens)",
    ("Queens", "Oakland Gardens-Hollis Hills"): "Oakland Gardens",
    ("Queens", "Pomonok-Electchester-Hillcrest"): "Pomonok / Hillcrest",
    ("Queens", "Queensbridge-Ravenswood-Dutch Kills"): "Queensbridge / Ravenswood",
    ("Queens", "Rockaway Beach-Arverne-Edgemere"): "Rockaway Beach / Arverne",
    ("Queens", "Whitestone-Beechhurst"): "Whitestone / Beechhurst",
    ("Queens", "Auburndale"): "Auburndale",
    ("Queens", "Bayside"): "Bayside",
    ("Queens", "Bellerose"): "Bellerose",
    ("Queens", "Cambria Heights"): "Cambria Heights",
    ("Queens", "College Point"): "College Point",
    ("Queens", "Corona"): "Corona",
    ("Queens", "East Elmhurst"): "East Elmhurst",
    ("Queens", "East Flushing"): "East Flushing",
    ("Queens", "Elmhurst"): "Elmhurst",
    ("Queens", "Forest Hills"): "Forest Hills",
    ("Queens", "Glendale"): "Glendale",
    ("Queens", "Hollis"): "Hollis",
    ("Queens", "Jackson Heights"): "Jackson Heights",
    ("Queens", "Jamaica"): "Jamaica",
    ("Queens", "Kew Gardens"): "Kew Gardens",
    ("Queens", "Kew Gardens Hills"): "Kew Gardens Hills",
    ("Queens", "Laurelton"): "Laurelton",
    ("Queens", "Maspeth"): "Maspeth",
    ("Queens", "Middle Village"): "Middle Village",
    ("Queens", "North Corona"): "North Corona",
    ("Queens", "Queens Village"): "Queens Village",
    ("Queens", "Queensboro Hill"): "Queensboro Hill",
    ("Queens", "Rego Park"): "Rego Park",
    ("Queens", "Richmond Hill"): "Richmond Hill",
    ("Queens", "Ridgewood"): "Ridgewood",
    ("Queens", "Rosedale"): "Rosedale",
    ("Queens", "South Ozone Park"): "South Ozone Park",
    ("Queens", "South Richmond Hill"): "South Richmond Hill",
    ("Queens", "St. Albans"): "St. Albans",
    ("Queens", "Sunnyside"): "Sunnyside",
    ("Queens", "Woodhaven"): "Woodhaven",
    ("Queens", "Woodside"): "Woodside",
    # Staten Island
    ("Staten Island", "Freshkills Park (North)"): None,
    ("Staten Island", "Freshkills Park (South)"): None,
    ("Staten Island", "Great Kills Park"): None,
    ("Staten Island", "Hoffman & Swinburne Islands"): None,
    ("Staten Island", "Miller Field"): None,
    ("Staten Island", "Snug Harbor"): None,
    (
        "Staten Island",
        "Annadale-Huguenot-Prince's Bay-Woodrow",
    ): "Annadale / Huguenot / Prince's Bay / Woodrow",
    ("Staten Island", "Arden Heights-Rossville"): "Arden Heights / Rossville",
    (
        "Staten Island",
        "Grasmere-Arrochar-South Beach-Dongan Hills",
    ): "Grasmere / Arrochar / South Beach / Dongan Hills",
    ("Staten Island", "Great Kills-Eltingville"): "Great Kills / Eltingville",
    (
        "Staten Island",
        "Mariner's Harbor-Arlington-Graniteville",
    ): "Mariners Harbor / Arlington / Graniteville",
    ("Staten Island", "New Dorp-Midland Beach"): "New Dorp / Midland Beach",
    (
        "Staten Island",
        "New Springville-Willowbrook-Bulls Head-Travis",
    ): "New Springville / Willowbrook / Bulls Head / Travis",
    ("Staten Island", "Oakwood-Richmondtown"): "Oakwood / Richmondtown",
    ("Staten Island", "Rosebank-Shore Acres-Park Hill"): "Rosebank / Shore Acres / Park Hill",
    ("Staten Island", "St. George-New Brighton"): "St. George / New Brighton",
    (
        "Staten Island",
        "Todt Hill-Emerson Hill-Lighthouse Hill-Manor Heights",
    ): "Todt Hill / Emerson Hill / Lighthouse Hill / Manor Heights",
    (
        "Staten Island",
        "Tompkinsville-Stapleton-Clifton-Fox Hills",
    ): "Tompkinsville / Stapleton / Clifton",
    ("Staten Island", "Tottenville-Charleston"): "Tottenville / Charleston",
    (
        "Staten Island",
        "West New Brighton-Silver Lake-Grymes Hill",
    ): "West New Brighton / Silver Lake / Grymes Hill",
    ("Staten Island", "Westerleigh-Castleton Corners"): "Westerleigh / Castleton Corners",
    ("Staten Island", "Fort Wadsworth"): "Fort Wadsworth",
    ("Staten Island", "Port Richmond"): "Port Richmond",
}

HIDDEN_ALIASES: dict[tuple[str, str], list[str]] = {
    ("South Jamaica", "Queens"): ["Baisley Park", "Baisley Pond"],
    ("Bay Ridge", "Brooklyn"): ["Fort Hamilton"],
    ("Springfield Gardens", "Queens"): ["Rochdale Village", "Brookville"],
    ("Jamaica Estates", "Queens"): ["Holliswood"],
    ("Soundview", "Bronx"): ["Clason Point", "Bruckner", "Bronx River"],
    ("Tompkinsville / Stapleton / Clifton", "Staten Island"): ["Fox Hills"],
    ("Ozone Park", "Queens"): ["Ozone Park (North)"],
    ("Hamilton Heights", "Manhattan"): ["Sugar Hill"],
    ("Windsor Terrace", "Brooklyn"): ["South Slope"],
    ("Kingsbridge / Marble Hill", "Bronx"): ["Kingsbridge Heights", "Van Cortlandt Village"],
    ("Ditmas Park", "Brooklyn"): ["Parkville"],
    ("Castle Hill", "Bronx"): ["Unionport"],
    ("Williamsbridge", "Bronx"): ["Olinville"],
    ("Howard Beach", "Queens"): ["Lindenwood"],
    ("Prospect Lefferts Gardens", "Brooklyn"): ["Wingate"],
    ("Flushing", "Queens"): ["Willets Point"],
    ("Oakland Gardens", "Queens"): ["Hollis Hills"],
    ("Mapleton", "Brooklyn"): ["Midwood (West)"],
    ("Astoria", "Queens"): ["Ditmars", "Steinway", "Hallets Point", "Old Astoria"],
    ("East New York", "Brooklyn"): ["City Line", "New Lots"],
    ("East Flatbush", "Brooklyn"): ["Erasmus", "Farragut", "Remsen Village", "Rugby"],
    ("Midtown", "Manhattan"): ["Times Square"],
    ("Flatiron / NoMad / Union Square", "Manhattan"): ["Midtown South"],
    ("Concourse", "Bronx"): ["Concourse Village"],
    ("Rockaway Beach / Arverne", "Queens"): ["Edgemere"],
}

CROSS_BOROUGH_ALIASES: dict[str, list[str]] = {
    "nyc-bronx-kingsbridge-marble-hill": ["Manhattan"],
}

ABBREVIATION_VARIANTS: dict[str, str] = {
    "Heights": "Hts",
    "Saint": "St",
    "Fort": "Ft",
    "Park": "Pk",
    "Point": "Pt",
    "Beach": "Bch",
}


def generate_display_key(market: str, borough: str, display_name: str) -> str:
    """Generate a stable, globally unique key for a selector item."""

    slug = display_name.lower()
    slug = slug.replace(" / ", "-")
    slug = re.sub(r"[^a-z0-9\-]", "", slug.replace(" ", "-"))
    slug = re.sub(r"-+", "-", slug).strip("-")
    borough_slug = borough.lower().replace(" ", "-")
    return f"{market}-{borough_slug}-{slug}"
