from decimal import Decimal

from pydantic import BaseModel

class StandardizedModel(BaseModel): ...
class Model(BaseModel): ...
class StrictModel(BaseModel): ...


class Money(Decimal): ...

STRICT_SCHEMAS: bool
