from __future__ import annotations

import re
from typing import Any, Dict, Optional, Tuple

from sqlalchemy.orm import Session
import ulid

from app.models.instructor import InstructorProfile
from app.models.service_catalog import (
    InstructorService,
    ServiceCatalog,
    ServiceCategory,
)

DEFAULT_DURATIONS = {30, 60}


def _ulid() -> str:
    """Generate a ULID string."""
    return str(ulid.ULID())


def _slugify(value: str) -> str:
    """Turn a service name into a slug suitable for ServiceCatalog."""
    value = value.strip().lower()
    slug = re.sub(r"[^a-z0-9]+", "-", value).strip("-")
    return slug or f"service-{_ulid().lower()}"


def _resolve_instructor_profile_id(
    session: Session,
    *,
    instructor_profile_id: Optional[str],
    instructor_id: Optional[str],
) -> str:
    """Translate a user/instructor id into an instructor_profile_id."""
    if instructor_profile_id:
        profile = (
            session.query(InstructorProfile)
            .filter(InstructorProfile.id == instructor_profile_id)
            .one_or_none()
        )
        if not profile:
            raise ValueError(f"Instructor profile {instructor_profile_id} not found")
        return profile.id

    if not instructor_id:
        raise ValueError("Must provide instructor_profile_id or instructor_id")

    profile = (
        session.query(InstructorProfile)
        .filter(InstructorProfile.user_id == instructor_id)
        .one_or_none()
    )
    if not profile:
        raise ValueError(f"Instructor profile for user {instructor_id} not found")
    return profile.id


def ensure_instructor_service_for_tests(
    session: Session,
    *,
    instructor_profile_id: Optional[str] = None,
    instructor_id: Optional[str] = None,
    service_name: str = "Piano",
    duration_minutes: int = 60,
    hourly_rate: float = 50.0,
    is_active: bool = True,
    extra_catalog_fields: Optional[Dict[str, Any]] = None,
    extra_instructor_service_fields: Optional[Dict[str, Any]] = None,
) -> Tuple[str, str]:
    """
    Ensure a concrete InstructorService exists for tests.

    Returns (service_catalog_id, instructor_service_id).
    """

    catalog_fields = dict(extra_catalog_fields or {})
    service_fields = dict(extra_instructor_service_fields or {})

    desired_durations = set(service_fields.get("duration_options", [])) | DEFAULT_DURATIONS
    desired_durations.add(duration_minutes)
    service_fields["duration_options"] = sorted(desired_durations)

    profile_id = _resolve_instructor_profile_id(
        session,
        instructor_profile_id=instructor_profile_id,
        instructor_id=instructor_id,
    )

    # Ensure we have a category
    category_id = catalog_fields.pop("category_id", None)
    if category_id is None:
        category = (
            session.query(ServiceCategory)
            .filter(ServiceCategory.slug == "testing-services")
            .one_or_none()
        )
        if not category:
            category = ServiceCategory(
                id=_ulid(),
                name="Testing Services",
                slug="testing-services",
                description="Autogenerated category for test utilities",
            )
            session.add(category)
            session.flush()
        category_id = category.id

    default_slug = _slugify(f"{service_name}-{profile_id}")
    catalog_slug = catalog_fields.pop("slug", default_slug)

    # Ensure catalog entry
    catalog = (
        session.query(ServiceCatalog)
        .filter(ServiceCatalog.slug == catalog_slug)
        .one_or_none()
    )
    if not catalog:
        catalog = ServiceCatalog(
            id=_ulid(),
            name=service_name,
            slug=catalog_slug,
            category_id=category_id,
            is_active=catalog_fields.pop("is_active", True),
            **catalog_fields,
        )
        session.add(catalog)
        session.flush()
    else:
        if is_active and not catalog.is_active:
            catalog.is_active = True

    # Ensure instructor service
    service = (
        session.query(InstructorService)
        .filter(
            InstructorService.instructor_profile_id == profile_id,
            InstructorService.service_catalog_id == catalog.id,
        )
        .order_by(InstructorService.created_at.desc())
        .first()
    )

    if service:
        current_options = set(service.duration_options or [])
        current_options |= desired_durations
        service.duration_options = sorted(current_options)
        if "hourly_rate" not in service_fields:
            service.hourly_rate = hourly_rate
        if "is_active" not in service_fields:
            service.is_active = is_active
        session.flush()
    else:
        service_kwargs = {
            "hourly_rate": hourly_rate,
            "duration_options": sorted(desired_durations),
            "is_active": is_active,
        }
        service_kwargs.update(service_fields)
        service = InstructorService(
            id=_ulid(),
            instructor_profile_id=profile_id,
            service_catalog_id=catalog.id,
            **service_kwargs,
        )
        session.add(service)
        session.flush()

    return catalog.id, service.id
