from collections.abc import Iterable, Iterator
from typing import Any, Optional


class Pipeline:
    def setex(self, name: str, time: int, value: str) -> "Pipeline": ...
    def execute(self) -> list[Any]: ...


class Redis:
    @classmethod
    def from_url(cls, url: str, **kwargs: Any) -> "Redis": ...

    def get(self, name: str) -> Optional[str]: ...
    def set(self, name: str, value: str, ex: Optional[int] = ..., px: Optional[int] = ..., nx: bool | None = ..., xx: bool | None = ...) -> bool: ...
    def setex(self, name: str, time: int, value: str) -> bool: ...
    def delete(self, *names: str) -> int: ...
    def eval(self, script: str, numkeys: int, *keys_and_args: Any) -> Any: ...
    def evalsha(self, sha: str, numkeys: int, *keys_and_args: Any) -> Any: ...
    def script_load(self, script: str) -> str: ...
    def ping(self) -> bool: ...
    def info(self, section: Optional[str] = ...) -> dict[str, Any]: ...
    def llen(self, name: str) -> int: ...
    def scan_iter(self, match: Optional[str] = ..., count: Optional[int] = ...) -> Iterator[str]: ...
    def mget(self, keys: Iterable[str]) -> list[Optional[str]]: ...
    def pipeline(self) -> Pipeline: ...


def from_url(url: str, **kwargs: Any) -> Redis: ...


class ConnectionError(Exception): ...


class TimeoutError(Exception): ...


__all__ = ["Redis", "Pipeline", "from_url", "ConnectionError", "TimeoutError"]
